import PDFDocument from 'pdfkit';

export function renderInvoicePdf(invoice) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 40, size: 'A4' });
    const chunks = [];

    doc.on('data', (chunk) => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    doc.fontSize(20).text('Qarwaan Travels Invoice', { align: 'left' });
    doc.moveDown(0.6);
    doc.fontSize(11).text(`Invoice Number: ${invoice.invoiceNumber}`);
    doc.text(`Issued At: ${new Date(invoice.issuedAt).toLocaleString()}`);
    doc.text(`Status: ${invoice.status}`);
    doc.text(`Currency: ${invoice.currency}`);
    doc.moveDown();

    doc.fontSize(13).text('Customer', { underline: true });
    doc.fontSize(11).text(`Name: ${invoice.customer.name}`);
    doc.text(`Email: ${invoice.customer.email}`);
    doc.text(`Phone: ${invoice.customer.phone}`);
    doc.moveDown();

    if (invoice.trip) {
      doc.fontSize(13).text('Trip', { underline: true });
      doc.fontSize(11).text(`Name: ${invoice.trip.name}`);
      doc.text(`Location: ${invoice.trip.location}`);
      doc.text(`Slug: ${invoice.trip.slug}`);
      doc.moveDown();
    }

    if (invoice.booking) {
      doc.fontSize(13).text('Booking', { underline: true });
      doc.fontSize(11).text(`Booking ID: ${invoice.booking.id}`);
      doc.text(`Travelers: ${invoice.booking.travelers}`);
      doc.text(`Travel Date: ${invoice.booking.travelDate || '-'}`);
      doc.text(`Booking Status: ${invoice.booking.bookingStatus}`);
      doc.moveDown();
    }

    doc.fontSize(13).text('Charges', { underline: true });
    invoice.lineItems.forEach((item) => {
      doc.fontSize(11).text(`${item.label}: ${invoice.currency} ${Number(item.amount).toLocaleString()}`);
    });
    doc.moveDown();

    doc.fontSize(13).text('Totals', { underline: true });
    doc.fontSize(11).text(`Subtotal: ${invoice.currency} ${invoice.totals.subtotal.toLocaleString()}`);
    doc.text(`Refunded: ${invoice.currency} ${invoice.totals.refunded.toLocaleString()}`);
    doc.text(`Net Paid: ${invoice.currency} ${invoice.totals.netPaid.toLocaleString()}`);
    doc.moveDown();

    if (invoice.refunds.length > 0) {
      doc.fontSize(13).text('Refund History', { underline: true });
      invoice.refunds.forEach((refund) => {
        doc
          .fontSize(10)
          .text(
            `${new Date(refund.createdAt).toLocaleString()} | ${invoice.currency} ${Number(refund.amount).toLocaleString()} | ${refund.reason || 'No reason'}`
          );
      });
    }

    doc.moveDown();
    doc.fontSize(10).fillColor('#666666').text('Generated by Qarwaan admin system.');
    doc.end();
  });
}
